name: 'Deploy to Azure App Service'
description: 'Deploys Docker image to Azure App Service with concurrency control'
inputs:
  app-name:
    description: 'Azure App Service name'
    required: true
  slot-name:
    description: 'Deployment slot name (default: Production)'
    required: false
    default: 'Production'
  image:
    description: 'Full image reference'
    required: true
  resource-group:
    description: 'Azure resource group'
    required: true
  environment:
    description: 'Environment name (for concurrency control)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      continue-on-error: false

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ inputs.app-name }}
        slot-name: ${{ inputs.slot-name }}
        images: ${{ inputs.image }}

    - name: Restart App Service
      shell: bash
      run: |
        az webapp restart \
          --name ${{ inputs.app-name }} \
          --resource-group ${{ inputs.resource-group }} \
          --output none

