name: 'Lint Code'
description: 'Runs linting, formatting, and type checking'
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Install linting dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pip install black isort flake8 mypy

    - name: Check formatting with Black
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: black --check src/ tests/ || (echo "❌ Black formatting check failed. Run 'black src/ tests/' to fix." && exit 1)

    - name: Check import sorting with isort
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: isort --check-only src/ tests/ || (echo "❌ Import sorting check failed. Run 'isort src/ tests/' to fix." && exit 1)

    - name: Run flake8
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: flake8 src/ tests/ || (echo "❌ Flake8 linting failed. Fix the issues above." && exit 1)

    - name: Run mypy type checking
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Run mypy with ignore-missing-imports for third-party packages
        mypy src/ --ignore-missing-imports || echo "⚠️  Type checking warnings (non-blocking)"

