name: 'Run Tests'
description: 'Runs pytest with coverage and uploads artifacts'
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  test-path:
    description: 'Test path'
    required: false
    default: 'tests/'
  coverage-threshold:
    description: 'Minimum coverage percentage'
    required: false
    default: '70'
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Install test dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pip install pytest pytest-cov pytest-asyncio pytest-mock httpx

    - name: Run tests with coverage
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        MONGO_URI: ${{ env.TEST_MONGO_URI }}
        APP_ENV: test
        PYTHONPATH: ${{ inputs.working-directory }}/src
      run: |
        pytest ${{ inputs.test-path }} \
          --cov=src/clinicai \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --cov-fail-under=${{ inputs.coverage-threshold }} \
          -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        files: ./${{ inputs.working-directory }}/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ inputs.python-version }}
        path: ${{ inputs.working-directory }}/htmlcov/

