name: 'Build and Push Docker Image'
description: 'Builds Docker image with BuildKit cache and pushes to ACR'
inputs:
  service-name:
    description: 'Service name'
    required: true
  acr-name:
    description: 'Azure Container Registry name'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: true
  context-path:
    description: 'Build context path'
    required: false
    default: '.'
  image-tag:
    description: 'Image tag (default: git SHA)'
    required: false
    default: '${{ github.sha }}'
  push:
    description: 'Push to registry'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.acr-name }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.acr-name }}.azurecr.io/${{ inputs.service-name }}
        tags: |
          type=sha,prefix={{branch}}-
          type=raw,value=${{ inputs.image-tag }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: ${{ inputs.push }} == 'true'
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Output image reference
      shell: bash
      run: |
        echo "image=${{ inputs.acr-name }}.azurecr.io/${{ inputs.service-name }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT

