name: 'Setup Python Environment'
description: 'Sets up Python with caching and dependencies'
inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.11'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  requirements-file:
    description: 'Requirements file path'
    required: false
    default: 'requirements.txt'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.working-directory }}/${{ inputs.requirements-file }}

    - name: Upgrade pip
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pip install -r ${{ inputs.requirements-file }}

