name: 'Send Notification'
description: 'Sends deployment notification to Slack/Teams/webhook'
inputs:
  webhook-url:
    description: 'Webhook URL (Slack/Teams)'
    required: false
  status:
    description: 'Deployment status (success/failure)'
    required: true
  environment:
    description: 'Environment name'
    required: true
  service-name:
    description: 'Service name'
    required: true
  commit-sha:
    description: 'Git commit SHA'
    required: false
    default: '${{ github.sha }}'
  commit-author:
    description: 'Commit author'
    required: false
    default: '${{ github.actor }}'
  workflow-run-url:
    description: 'Workflow run URL'
    required: false
    default: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

runs:
  using: 'composite'
  steps:
    - name: Send notification
      shell: bash
      if: inputs.webhook-url != ''
      env:
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        STATUS: ${{ inputs.status }}
        ENV: ${{ inputs.environment }}
        SERVICE: ${{ inputs.service-name }}
        SHA: ${{ inputs.commit-sha }}
        AUTHOR: ${{ inputs.commit-author }}
        RUN_URL: ${{ inputs.workflow-run-url }}
      run: |
        if [ "$STATUS" = "success" ]; then
          COLOR="good"
          EMOJI="✅"
        else
          COLOR="danger"
          EMOJI="❌"
        fi
        
        # Slack/Teams compatible webhook payload
        PAYLOAD=$(cat <<EOF
        {
          "text": "${EMOJI} Deployment ${STATUS}: ${SERVICE} to ${ENV}",
          "attachments": [{
            "color": "${COLOR}",
            "fields": [
              {"title": "Environment", "value": "${ENV}", "short": true},
              {"title": "Service", "value": "${SERVICE}", "short": true},
              {"title": "Status", "value": "${STATUS}", "short": true},
              {"title": "Commit", "value": "${SHA:0:7}", "short": true},
              {"title": "Author", "value": "${AUTHOR}", "short": true},
              {"title": "Workflow", "value": "<${RUN_URL}|View Run>", "short": true}
            ]
          }]
        }
        EOF
        )
        
        curl -X POST -H 'Content-type: application/json' \
          --data "$PAYLOAD" \
          "$WEBHOOK_URL" || echo "⚠️  Failed to send notification"

